
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enrico
 */
public class PanelHelp extends javax.swing.JPanel {

    public static int getABORT() {
        return ABORT;
    }
    BufferedImage img_hantu_bingung;
    Image img_hantu_diam;
    Image img_hantu_normal;
    Image img_player;
    Image img_power_bingung;
    Image img_power_diam;
    ArrayList<JLabel> lbl=new ArrayList<>();
    /**
     * Creates new form PanelHelp
     */
    public PanelHelp() {
        initComponents();
        //imagesource="Src\\Char\\bingun.png";
        gambar_hantu_bingung("Src\\Char\\bingung.png");
        gambar_hantu_diam("Src\\Char\\diam.png");
        gambar_hantu_normal("Src\\Char\\ghost_0_0.png");
        gambar_player("Src\\Char\\pacmankanan.png");
        gambar_power_bingung("Src\\Char\\stroberi.png");
        gambar_power_diam("Src\\Char\\105.png");
        repaint();
    }
    Graphics2D g2;
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g2=(Graphics2D) g;
        g2.setFont(new Font("Arial", 1, 10));
        g2.setColor(Color.BLACK);
        g2.drawImage(img_hantu_bingung,10,0,32,32,null);
        g2.drawString("Bingung",5,40);
        g2.drawImage(img_hantu_diam,90,0,32,32,null);
        g2.drawString("Diam",93,40);
        g2.drawImage(img_hantu_normal,170,0,32,32,null);
        g2.drawString("Normal",170,40);
        g2.drawImage(img_player,30,60,32,32,null);
        g2.drawString("Player", 30, 100);
        g2.setColor(Color.yellow);
        g2.fillOval(150, 60, 32, 32);
        g2.setColor(Color.BLACK);
        g2.drawString("Makanan", 145, 100);
        g2.drawImage(img_power_bingung,30,120,32,32,null);
        g2.drawString("Power Up Confuse",0, 160);
        g2.drawImage(img_power_diam,160,120,32,32,null);
        g2.drawString("Power up Diam", 140, 160);
    }
    public void gambar_power_diam(String Source){
    try {
            img_power_diam=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void gambar_power_bingung(String Source){
        try {
            img_power_bingung=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void gambar_hantu_bingung(String Source){
        try {
            img_hantu_bingung=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void gambar_hantu_diam(String Source){
        try {
            img_hantu_diam=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void gambar_hantu_normal(String Source){
        try {
            img_hantu_normal=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void gambar_player(String Source){
         try {
            img_player=ImageIO.read(new File(Source));
        } catch (IOException ex) {
            Logger.getLogger(HelpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
